name: PGF-CI-LAB-FIN

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Descarga repositorio Lab Final
     
          
      run: |
        echo "PGF-Pipeline-Test"
