name: PGF-CI-LAB-FIN

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
    - name: Ejecuta mensaje  
    #.cambiar por compilacion y agregar copia de Jar a raiz del proyecto       
      run: |
        echo "PGF-Pipeline-Test"

  Sast:
    needs: build    
    runs-on: ubuntu-latest
   
    steps:

    - name: Descarga repositorio Lab Final
      uses: actions/checkout@v4
        
    - name: SAST-SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=pgf-devsecops
          -Dsonar.projectKey=PGF-DevSecOps_PGF-DevSecOps-Ciclo-7-final-lab
          -Dsonar.host.url=https://sonarcloud.io/
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  SCA:
    runs-on: ubuntu-latest
    needs: build
    
    steps:

    - name: Descarga repositorio
      uses: actions/checkout@v3

    #- name: Compilacion JAVA
      #run: |
        #chmod +x gradlew
        #./gradlew build

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
 
    - name: Install Dependencies
      run: npm install
    
    #- name: Run Action
      #run: node index.js

    - name: SCA-Dependency-check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      with:
        project: 'PGF-DevSecOps-Ciclo-7-final-lab'
        path: '.'
        format: 'HTML'

    - name: Subir resultados reporte Dep-check
      uses: actions/upload-artifact@master
      with:
        name: Reporte PG-Dependency-check 
        path: ${{github.workspace}}/reports     


  Trivi:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
    #- name: Build Docker
      #run: !
        #docker build --tag pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest

    #- name: Build Docker
      #run: !
        #docker build --tag pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest
        #docker push pamelagarciafarias/netflix:latest
    
    # Agregar analisis de imagen con trivi   
   
    
    #- name: Push Docker
      #run: !
        #docker push pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab
    
    
    # agregar desplkiegue con minikube
    
  #Minikube:
    #runs-on: ubuntu-latest
    #needs: build
    
    #steps:
    #- name:   

 # agregar analisis de DAST con Owasp ZAP
    
  #Owasp ZAP:
    #runs-on: ubuntu-latest
    #needs: build
    
    #steps:
    #- name:          
