name: PGF-CI-LAB-FIN

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Descarga repositorio Lab Final
     
          
      run: |
        echo "PGF-Pipeline-Test"

    #- name: SAST-SonarCloud
      #uses: sonarsource/sonarcloud-github-action@master
      #with:
        #projectBaseDir: .
        #args: >
          #-Dsonar.organization=pgf-devsecops
          #-Dsonar.projectKey=PGF-DevSecOps_PGF-DevSecOps-Ciclo-7-final-lab
          #-Dsonar.host.url=https://sonarcloud.io/
      #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #PGF-SONAR_TOKEN: ${{ secrets.PGF-SONAR_TOKEN }}

