name: PGF-CI-LAB-FIN

on:
  push:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: SCA-Dependency-check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: "PGF-DevSecOps-Ciclo-7-final-lab"
          path: "."
          format: "HTML"

      - name: Subir resultados reporte Dep-check
        uses: actions/upload-artifact@master
        with:
          name: Reporte PG-Dependency-check
          path: ${{github.workspace}}/reports

  sonar-check:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: SAST-SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=pgf-devsecops
            -Dsonar.projectKey=PGF-DevSecOps_PGF-DevSecOps-Ciclo-7-final-lab
            -Dsonar.host.url=https://sonarcloud.io/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: [dependency-check, sonar-check]
    runs-on: ubuntu-latest
    steps:
      - name: Descarga repositorio
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker
        run: docker build --tag pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest"
          format: "table"
          #exit-code: "1"
          #vuln-type: "os,library"
          #severity: "CRITICAL,HIGH,MEDIUM"
          
      - name: Push to Docker registry
        run: docker push pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab

 
      - name: Pull de la Imagen Docker
        run: |
          docker pull pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest

      - name: Despliegue de themoviedb
        run: |
          docker run -p 8080:8085 --name themoviedb-deploy -d pamelagarciafarias/pgf-devsecops-ciclo-7-final-lab:latest

      - name: Sleep
        run: | 
          sleep 30


    #- name: OWASP ZAP Scan
      #uses: zaproxy/action-baseline@v0.11.0
      #with:
          #target: 'http://localhost:8080/'

 
