name: PGF-CI-LAB-FIN

on:
  
  push:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
    - name: Ejecuta mensaje         
      run: |
        echo "PGF-Pipeline-Test"

  Sast:
    needs: build    
    runs-on: ubuntu-latest
   
    steps:

    - name: Descarga repositorio Lab Final
      uses: actions/checkout@v4
        
    - name: SAST-SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=pgf-devsecops
          -Dsonar.projectKey=PGF-DevSecOps_PGF-DevSecOps-Ciclo-7-final-lab
          -Dsonar.host.url=https://sonarcloud.io/
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  SCA:
    runs-on: ubuntu-latest
    needs: build
    
    steps:

    - name: Descarga repositorio
      uses: actions/checkout@v3

    #- name: Compilacion JAVA
      #run: |
        #chmod +x gradlew
        #./gradlew build

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
 
    - name: Install Dependencies
      run: npm install
    
    - name: Run Action
      run: node index.js

    #- name: SCA-Dependency Check
      #uses: dependency-check/Dependency-Check_Action@1.1.0
      #with:
        #project: 'PGF-DevSecOps-Ciclo-7-final-lab'
        #path: '.'
        #format: 'HTML'
